### ISSUE TITLE
xdcc-search subsplease stopped working

### ISSUE THREAD

**Issue by qwasy** [namboy94/xdcc-dl#21]
I'm using xdcc-dl 5.1.0, and since a few days, the search is not working anymore. 
This is the error log:

Traceback (most recent call last):
  File "/usr/local/bin/xdcc-search", line 63, in <module>
    exit_msg="Thanks for using xdcc-dl!"
  File "/usr/local/lib/python3.7/dist-packages/puffotter/init.py", line 74, in cli_start
    main_func(args)  # type: ignore
  File "/usr/local/bin/xdcc-search", line 37, in main
    results = search_engine.search(args.search_term)
  File "/usr/local/lib/python3.7/dist-packages/xdcc_dl/pack_search/SearchEngine.py", line 49, in search
    return self._procedure(term)
  File "/usr/local/lib/python3.7/dist-packages/xdcc_dl/pack_search/procedures/subsplease.py", line 47, in find_subsplease_packs
    result = parse_result(result)
  File "/usr/local/lib/python3.7/dist-packages/xdcc_dl/pack_search/procedures/subsplease.py", line 90, in parse_result
    key, content = part.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
 
I tried the search with nibl, which didn't show any results (even though the anime is on their website). ixirc and xdcc-eu are showing some results.
I tried it with Python 3.7.3 and Python 3.8.10, with Ubuntu on a VPS, and Dietpi on a local RPi4. I upgraded all pip installations to the newest version, with no difference.

Is there anything I could try?
Or do you need any more informations?

**Comment by namboy94** [comment]
Hi, it seems that something changed on the subsplease site in regards to CloudFlare, which makes it impossible for me to scrape the packlist. I'm honestly a bit stumped on how to circumvent that, since cfscrape no longer seems to work.

I'm in the process of at least getting the nibl search running again (They redesigned the website some time ago, which broke the search feature in xdcc-dl)

nibl does seem to have all the packs available as subsplease, so it shouldn't be too huge a deal if the subsplease search won't work (at least until cfscrape gets updated or I find another solution)

**Comment by namboy94** [comment]
The new version (5.2.0) is now available. It fixes the nibl search engine and adds a notice to the subsplease search engine that it's currently non-functional.

If cfscrape were to ever be updated to work again, it should start working again on its own.

**Comment by qwasy** [comment]
That works, thank you
